### ISSUE TITLE
Cant root

### ISSUE THREAD

**Issue by abhayruparel** [AOSGP/Changelog#1]
Tried everything including fully wiping device and reflashing the latest build.

**Comment by abhayruparel** [comment]
Got root access after downloading supersu zip from settings about phone. I want to use magisk hide so installed apk and magisk installer zip. Still while using magisk hide for snapchat it fails to hide and snapchat doesn't allow to login. In previous build magisk worked like charm.

**Comment by dimusa6** [comment]
I think that your problem it´s cause by old su integrated in cm (we change to new one now. In the tomorrow compilation, it will be fix)

**Comment by abhayruparel** [comment]
Not able to check ota error: "Can't check updates" .

**Comment by dimusa6** [comment]
We recently change the server, and also OTA is search in the old server yet. When all devices compile, I will tell yo you for check it!

**Comment by abhayruparel** [comment]
Waiting for update.

**Comment by abhayruparel** [comment]
Solved.
