### ISSUE TITLE
Showing charging when charger isn't connected

### ISSUE THREAD

**Issue by abhayruparel** [AOSGP/Changelog#4]
Device name:- Lenovo p2
Logs?
-sent to dimusa6 on telegram
How can you reproduce same condition?
- connect device to pc in transfer file mode and remove the cable still on lock screen it will show charging here is a video http://clkmein.com/qVyfmU
Also please note this is second time I'm opening the same issue. Last time I opened a video you have said that it is resolved but it isn't.

**Comment by redking12** [comment]
@dimusa username of telegram on which logs are send
